### PR TITLE
Reduce sidebar width on product modal at tablet sizes

### PR DESCRIPTION
**Pull request by markjamieson**
## Reason for change

Fixes https://app.zenhub.com/workspaces/engineering-56990653b8516b1b4867e8b2/issues/manifoldco/engineering/9469

## Testing

Open a product modal on render, adjust width through the various breakpoints

## Checklist

- [ ] **CHANGELOG**: The **Unreleased** section of CHANGELOG was updated
- [ ] **Prop changes**: [docs][docs] were updated
- [ ] **Prop changes**: E2E tests were updated, testing from the highest level possible
- [ ] **Platform testing**: If this change should be [tested against a platform][platform-testing], has it been?

[docs]: https://ui.sandbox.manifold.co
[platform-testing]: https://app.gitbook.com/@manifold/s/engineering/playbooks/testing-your-code-against-a-platform

### CODE REVIEW

**Comment by dangodev** [comment]
I’m scared this won’t fix the problem well because it relies on window width. As in the case with our platforms, sometimes this is in a wrapper that isn’t full-window-width. For that reason, perhaps an approach using CSS Grid would be better—that actually responds based on the size of the columns rather than the browser width. Example: https://labs.jensimmons.com/2017/03-009.html

**Comment by markjamieson** [comment]
This seems to fix the problem for me. @davidleger95 mentioned JS media queries in the original issue, but I'm not sure why those are needed. I might be oversimplifying!

The original problem comes from the screenshot menu having an absolute width (4rem * number of items), and just not having enough room to display in the grid at tablet width. Reducing the sidebar seemed to work, but we could also look at having an overflow scroll on just that menu.

**Comment by dangodev** [comment]
@markjamieson what about this, instead of all the media queries?

```css
.grid {
  grid-template-columns: repeat(auto-fit, minmax(12rem, max-content))
}
```

Something like this just auto-wraps when either column goes smaller than an arbitrary width (here, `12rem`). I’m fine with this fix, but something like this which is a function of content size rather than browser size may last us a little longer?

**Comment by dangodev** [comment]
Ah sorry; wasn’t trying to strongarm this; just was scared that once this component was touched again in the future we’d reintroduce the problem for platforms.

If we go with this, then be sure to remove all the `grid-template-columns` in the other media queries as well.

**Comment by markjamieson** [comment]
I don't understand your solution well enough to figure out how to fix the issues I'm having with it, and I have to put it aside for a bit. I've done barely anything though, so if you want to take over please feel free. I was just hoping to knock this one out quick.

**Comment by dangodev** [comment]
Let’s go with your tested fix then if it works for now. Sorry for blocking this. I can explain more reasoning later but my solution was half-baked here.

**Comment by markjamieson** [comment]
My fix only works if the max number of screenshots is 3. I can't remember if that's the case. And obviously that's not very robust CSS.

**Pull request merged**
