### PR TITLE
Update local oauth url

### PR DESCRIPTION
**Pull request by gclapperton**
## Reason for change

This [logo PR](https://github.com/manifoldco/logo/pull/556) updated the location of the OAuth endpoint in docker compose. We need to update UI to match

## Testing

No functionality changes. Test with docker compose

## Checklist

- [ ] **CHANGELOG**: The **Unreleased** section of CHANGELOG was updated
- [ ] **Prop changes**: [docs][docs] were updated
- [ ] **Prop changes**: E2E tests were updated, testing from the highest level possible
- [ ] **Platform testing**: If this change should be [tested against a platform][platform-testing], has it been?

[docs]: https://ui.sandbox.manifold.co
[platform-testing]: https://app.gitbook.com/@manifold/s/engineering/playbooks/testing-your-code-against-a-platform

### CODE REVIEW

**Comment by domenicrosati** [comment]
Both currently work but this is better

**Comment by gclapperton** [comment]
> Both currently work but this is better

@domenicrosati Both URLs? I started my docker-compose env from scratch, but was unable to authenticate with UI locally. Took me a while to track down, but this sorted it

I'm a bit confused by the rolling update in docker-compose terms, but let me know when it's done, so that I can revert these changes locally.

Closing

**Comment by domenicrosati** [comment]
@gclapperton  OHHHH i know why hahah yes ok I am reopening this it's fine to merge this there was an additional config change that would'nt make both work! thanks for opening this

**Comment by gclapperton** [comment]
Ok, thanks @domenicrosati !

**Pull request merged**
