### PR TITLE
top-level and cards theme refinements

### PR DESCRIPTION
**Pull request by davidleger95**
## Reason for change

- Add border state variables
- Refactor Cards theming
- Add white outline to logos to ensure they're always properly contrasted for all themes.

## Testing

Check theming still works as expected for all components on all themes

### CODE REVIEW

**Comment by davidleger95** [comment]
bleh, my stylelint broke down earlier.  🔧

**Comment by sslotsky** [comment]
I thought the Manifold theme was still using gradient buttons? I can't tell the difference currently between the Manifold theme and the Default theme in the plan selector.

image

**Comment by davidleger95** [comment]
> I thought the Manifold theme was still using gradient buttons?

Oops, I got distracted moving some theme variables and forgot to paste them after cutting them 😂

**Comment by davidleger95** [comment]
It's fixed now @sslotsky :)

**Pull request merged**
